export const CAREER_JOBS = 'CAREER_JOBS';
export const PROFILE_PERSONAL_INFO = 'PROFILE_PERSONAL_INFO';
export const PROFILE_DESCRIPTION = 'PROFILE_DESCRIPTION';
export const PROFILE_SOCIAL_MEDIA = 'PROFILE_SOCIAL_MEDIA';
export const PROFILE_EXPERIENCES = 'PROFILE_EXPERIENCES';
export const PROFILE_EDUCATION = 'PROFILE_EDUCATION';
export const TENANT_DETAILS = 'TENANT_DETAILS';
export const RESUME_DETAILS = 'RESUME_DETAILS';
export const CURRENT_BOTTOM_TAB = 'CURRENT_BOTTOM_TAB';
export const PROFILE_SKILLS = 'PROFILE_SKILLS'
export const PROFILE_PREFERENCES = 'PROFILE_PREFERENCES'
export const USER_PREFS = 'USER_PREFS'
export const SESSION = 'SESSION'









